spring:
  datasource:
    url: jdbc:h2:mem:credfacil_db
    username: tiago
    password:
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
server:
  error:
    include-message: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
